module.exports = function (grunt) {

    var glob = require("glob"),
        fs   = require("fs"),
        path = require("path"),
        _ = grunt.util._;

    grunt.registerTask('generatemocks', 'Prepare Mocks for Unit Tests', function(){
        var opts = grunt.task.current.options();

        generateMocks(opts.mocks);
    });

    function generateMocks(mockdir) {
        var output = [];

        output.push("//----------------------------------------------------");
        output.push("// NOTE: DO NOT Modify this file! it's automatically generated by a Grunt task (see build-tasks/generatemocks.js)");
        output.push("//----------------------------------------------------");
        output.push("module.exports = {");

        files = glob.sync(mockdir + '**/*.js');
        _.each(files, function(file, index) {
            var key = path.basename(file, path.extname(file));
            output.push( (index > 0 ? "," : "") + "  '" + key + "': require('./" + path.basename(file, path.extname(file)) + "')" );
        });
        output.push("};");
        fs.writeFileSync(mockdir + "/index.js", output.join('\n'));
    }
};

