//----------------------------------------------------
// NOTE: DO NOT Modify this file! it's automatically generated by a Grunt task (see build-tasks/generatemocks.js)
//----------------------------------------------------
module.exports = {
  'index': require('./index')
};